[package]
name = "kooha"
version = "1.2.1"
authors = ["Dave Patrick <davecruz48@gmail.com>"]
license = "GPL-3.0-or-later"
edition = "2018"

[dependencies]
anyhow = "1.0"
chrono = "0.4"
strum = "0.21.0"
strum_macros = "0.21.0"
log = "0.4"
pretty_env_logger = "0.4"
once_cell = "1.5"
gettext-rs = { version = "0.7", features = ["gettext-system"] }
ashpd = { version = "0.2.0-alpha-3", features = ["feature_gtk4"] }
gtk = { package = "gtk4", version = "0.2" }
adw = { package = "libadwaita", version = "0.1.0-alpha-3" }
gst = { package = "gstreamer", version = "0.17" }
gst-plugin-gif = "0.7.0"
futures = "0.3.16"
