[package]
name = "kooha"
version = "0.1.0"
authors = ["SeaDve <davecruz48@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
chrono = "0.4"
log = "0.4"
pretty_env_logger = "0.4"
once_cell = "1.5"
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gtk = { package = "gtk4", version = "0.2" }
adw = { package = "libadwaita", version = "0.1.0-alpha" }
gst = { package = "gstreamer", version = "0.17" }
gst-plugin-gif = "0.7.0"
futures = "0.3"

[dependencies.ashpd]
git = "https://github.com/bilelmoussaoui/ashpd"
features = ["feature_gtk4"]
