[package]
name = "kooha"
version = "2.2.3"
authors = ["Dave Patrick Caberto <davecruz48@gmail.com>"]
license = "GPL-3.0-or-later"
edition = "2021"

[profile.release]
lto = true

[dependencies]
anyhow = "1.0.59"
tracing = "0.1.36"
tracing-subscriber = "0.3.15"
once_cell = "1.9.0"
gettext-rs = { version = "0.7.0", features = ["gettext-system"] }
gtk = { package = "gtk4", version = "0.5.4" }
gdk-wayland = { package = "gdk4-wayland", version = "0.5.4" }
gdk-x11 = { package = "gdk4-x11", version = "0.5.4" }
adw = { package = "libadwaita", version = "0.2.1", features = ["v1_2"] }
gst_video = { package = "gstreamer-video", version = "0.19.4" }
gst_pbutils = { package = "gstreamer-pbutils", version = "0.19.2", features = [
    "v1_20",
] }
gst = { package = "gstreamer", version = "0.19.4" }
gst-plugin-gif = "0.9.2"
gst-plugin-gtk4 = "0.9.3"
futures-channel = "0.3.19"
futures-util = { version = "0.3", default-features = false }
gsettings-macro = "0.1.11"
pulse = { package = "libpulse-binding", version = "2.26.0" }
pulse_glib = { package = "libpulse-glib-binding", version = "2.25.1" }
