[package]
name = "kooha"
version = "2.0.1"
authors = ["Dave Patrick Caberto <davecruz48@gmail.com>"]
license = "GPL-3.0-or-later"
edition = "2021"

[dependencies]
error-stack = "0.1.1"
tracing = "0.1.36"
tracing-subscriber = "0.3.15"
once_cell = "1.9.0"
gettext-rs = { version = "0.7.0", features = ["gettext-system"] }
gtk = { package = "gtk4", version = "0.4.5" }
gdk-wayland = { package = "gdk4-wayland", version = "0.4.5" }
gdk-x11 = { package = "gdk4-x11", version = "0.4.5" }
adw = { package = "libadwaita", version = "0.2.0-alpha.2", features = ["v1_2"] }
gst = { package = "gstreamer", version = "0.18.2" }
gst-plugin-gif = "0.8.0"
futures-channel = "0.3.19"
futures-util = "0.3.19"
gsettings-macro = "0.1.11"
