[package]
name = "kooha"
version = "0.1.0"
authors = ["SeaDve <davecruz48@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
pretty_env_logger = "0.4"
gettext-rs = { version = "0.7", features = ["gettext-system"] }
adw = {package = "libadwaita", version = "0.1.0-alpha"}
gtk = {package = "gtk4", version = "0.1"}
gst = {package = "gstreamer", version = "0.17"}
ashpd = "0.1"
enumflags2 = "0.6"
zbus = "1.1"
gst-plugin-gif = "0.7.0"
gtk-macros = "0.3"
once_cell = "1.5"
