[package]
name = "kooha"
version = "2.0.1"
authors = ["Dave Patrick <davecruz48@gmail.com>"]
license = "GPL-3.0-or-later"
edition = "2021"

[dependencies]
anyhow = "1.0.53"
strum = "0.24.0"
strum_macros = "0.24.0"
log = "0.4.14"
pretty_env_logger = "0.4.0"
once_cell = "1.9.0"
gettext-rs = { version = "0.7.0", features = ["gettext-system"] }
ashpd = { version = "0.3.2", features = ["feature_gtk4"] }
gtk = { package = "gtk4", version = "0.4.5" }
adw = { package = "libadwaita", version = "0.1.0" }
gst = { package = "gstreamer", version = "0.18.2" }
gst-plugin-gif = "0.8.0"
futures-channel = "0.3.19"
pulsectl-rs = "0.3.2"
gsettings-macro = "0.1.11"

[dev-dependencies]
approx = "0.5.1"
